name: Go build


on:
  push:
    branches: [ main, feat/*, rc/* ]
  pull_request:
    branches: [ main, feat/*, rc/* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.7
        id: go

      - name: Checkout mx-chain-go
        uses: actions/checkout@v4
        with:
          repository: 'multiversx/mx-chain-go'
          ref: 'feat/chain-go-sdk'
          path: 'mx-chain-go'

      - name: Checkout mx-chain-simulator-go
        uses: actions/checkout@v4
        with:
          repository: 'multiversx/mx-chain-simulator-go'
          path: 'mx-chain-simulator-go'

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        run: |
          cd mx-chain-simulator-go/cmd/chainsimulator 
          go build
